/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import BDMySQL.ConectorMySQL;
import inicio.inicio;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Desktop;


/**
 *
 * @author anoni
 */
public class cli extends javax.swing.JFrame {
     ConectorMySQL conec = new ConectorMySQL();
    Connection conectar =conec.Conectar();


    

    /**
     * Creates new form cli
     */
    public cli() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setSize(980,866);
        this.setLocationRelativeTo(null);
        

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelRound1 = new interfaz.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        ID1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        N1 = new javax.swing.JTextField();
        CA1 = new javax.swing.JTextField();
        PRE1 = new javax.swing.JTextField();
        DES1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        modi1 = new javax.swing.JButton();
        add1 = new javax.swing.JButton();
        dele1 = new javax.swing.JButton();
        search = new javax.swing.JButton();
        panelRound2 = new interfaz.PanelRound();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        web = new javax.swing.JButton();
        log = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 89, 45));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 280, -1, -1));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setToolTipText("");
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Codigo:");

        ID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Precio:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Cantidad");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Descripcion:");

        N1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N1ActionPerformed(evt);
            }
        });

        CA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CA1ActionPerformed(evt);
            }
        });

        PRE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRE1ActionPerformed(evt);
            }
        });

        DES1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DES1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("INVENTARIO");

        modi1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        modi1.setForeground(new java.awt.Color(0, 0, 0));
        modi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/img/modify.ai.png"))); // NOI18N
        modi1.setText("Modificar");
        modi1.setBorder(null);
        modi1.setContentAreaFilled(false);
        modi1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modi1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/img/mod2.png"))); // NOI18N
        modi1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        add1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        add1.setForeground(new java.awt.Color(0, 0, 0));
        add1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/img/add2.png"))); // NOI18N
        add1.setText("Agregar");
        add1.setBorder(null);
        add1.setContentAreaFilled(false);
        add1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/img/add3.png"))); // NOI18N
        add1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });

        dele1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dele1.setForeground(new java.awt.Color(0, 0, 0));
        dele1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/img/dele1i.png"))); // NOI18N
        dele1.setText("Eliminar");
        dele1.setBorder(null);
        dele1.setContentAreaFilled(false);
        dele1.setDisabledIcon(null);
        dele1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dele1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/img/dele2.png"))); // NOI18N
        dele1.setVerifyInputWhenFocusTarget(false);
        dele1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dele1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dele1ActionPerformed(evt);
            }
        });

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/img/search.png"))); // NOI18N
        search.setBorder(null);
        search.setBorderPainted(false);
        search.setContentAreaFilled(false);
        search.setDefaultCapable(false);
        search.setFocusPainted(false);
        search.setFocusable(false);
        search.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/img/search2.png"))); // NOI18N
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRound1Layout.createSequentialGroup()
                                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(6, 6, 6)))
                                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(PRE1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                        .addComponent(CA1)
                                        .addComponent(ID1))
                                    .addComponent(N1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DES1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(107, 107, 107))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(add1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modi1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(dele1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4))
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(N1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(PRE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(DES1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dele1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modi1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 410, 580));

        panelRound2.setBackground(new java.awt.Color(6, 47, 64));
        panelRound2.setRoundBottomRight(70);
        panelRound2.setRoundTopRight(70);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Krockbites ");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        web.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        web.setForeground(new java.awt.Color(255, 255, 255));
        web.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/img/brow.png"))); // NOI18N
        web.setText("Pagina web");
        web.setBorder(null);
        web.setBorderPainted(false);
        web.setContentAreaFilled(false);
        web.setDefaultCapable(false);
        web.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        web.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/img/brow2.png"))); // NOI18N
        web.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        web.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(web, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(web, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(600, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 830));

        log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/img/logo4.png"))); // NOI18N
        log.setBorder(null);
        log.setBorderPainted(false);
        log.setContentAreaFilled(false);
        log.setDefaultCapable(false);
        log.setFocusPainted(false);
        log.setFocusable(false);
        log.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/img/logo5.png"))); // NOI18N
        jPanel1.add(log, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID1ActionPerformed
       
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_ID1ActionPerformed

    private void N1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_N1ActionPerformed

    private void CA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CA1ActionPerformed

    private void PRE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRE1ActionPerformed

    private void DES1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DES1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DES1ActionPerformed

    private void webActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webActionPerformed
        // TODO add your handling code here:
        if (java.awt.Desktop.isDesktopSupported()) {
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
        if (desktop.isSupported(java.awt.Desktop.Action.BROWSE)) {
        try {
                java.net.URI uri = new java.net.URI("https://catfee-sv.github.io/");
                desktop.browse(uri);
        } catch (Exception e) {

                } 
            }
        }
    }//GEN-LAST:event_webActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        inicio newframe=new inicio();
        newframe.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_searchActionPerformed

    private void dele1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dele1ActionPerformed
        // TODO add your handling code here:
        Guardar();

        ID1.setText("");
        N1.setText("");
        CA1.setText("");
        PRE1.setText("");
        DES1.setText("");

    }//GEN-LAST:event_dele1ActionPerformed

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed

        Guardar();

        ID1.setText("");
        N1.setText("");
        CA1.setText("");
        PRE1.setText("");
        DES1.setText("");

    }//GEN-LAST:event_add1ActionPerformed

    
    
    
    
    
     public void Guardar(){ 
              String Codigo = ID1.getText();
    String Nombre = N1.getText();
    String CantidadStr = CA1.getText(); // Guardamos la cantidad como String temporalmente
    String PrecioStr = PRE1.getText(); // Guardamos el precio como String temporalmente
    String Descripcion = DES1.getText();
    String Sql = "INSERT INTO inventario (codigo, nombre, cantidad, precio, descripcion) VALUES(?,?,?,?,?)";

        
             try {
            
                 Statement  set=conectar.createStatement();
                 ResultSet resultado=set.executeQuery("Select*from inventario where codigo like'"+ID1.getText()+"'");
             
             if(resultado.next()){
                getToolkit().beep();
                JOptionPane.showMessageDialog(null,"Producto ya existe");
                ID1.requestFocus();
                
             }else if(ID1.getText().isEmpty()){
                getToolkit().beep();
                JOptionPane.showMessageDialog(null,"Codigo de barra bligatoria");
             ID1.requestFocus();
             }else{
                 int Cantidad = Integer.parseInt(CantidadStr);
            int Precio = Integer.parseInt(PrecioStr); 
               PreparedStatement pasar =conectar.prepareStatement(Sql);
             pasar.setString(1, Codigo);
                pasar.setString(2, Nombre);
                pasar.setString(3, CantidadStr);
             pasar.setInt(4, Precio);
             pasar.setString(5, Descripcion);
             pasar.executeUpdate();
             JOptionPane.showMessageDialog(null,"Registro Exitoso");
             }
             } catch (SQLException ex) {
             Logger.getLogger(cli.class.getName()).log(Level.SEVERE, null, ex);
             
             
         }
     }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CA1;
    private javax.swing.JTextField DES1;
    private javax.swing.JTextField ID1;
    private javax.swing.JTextField N1;
    private javax.swing.JTextField PRE1;
    private javax.swing.JButton add1;
    private javax.swing.JButton dele1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton log;
    private javax.swing.JButton modi1;
    private interfaz.PanelRound panelRound1;
    private interfaz.PanelRound panelRound2;
    private javax.swing.JButton search;
    private javax.swing.JButton web;
    // End of variables declaration//GEN-END:variables
}
